on:
 push:
name: Azure Bicep Deployment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     -  uses: actions/checkout@v2
     -  name: validation only
        run: |
          az bicep build --file sampl.bicep
     -  name: Deployment
        run: |
          az login
          az deployment group create --resource-group rg3 --template-file sampl.bicep
      
       
