on: 
  push
name: Azure Bicep
jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
     
     #checkout code
       - uses: actions/checkout@main
       - name: validate
         run: |
          az bicep build --file sampl.bicep
       - name:Deploy   
         run: |
          az login 
          az deployment group create --resource-group rg2 --template-File sampl.bicep
